version: "3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ..:/workspace:cached
      - commandhistory:/commandhistory
    command: sleep infinity
    environment:
      - HISTFILE=/commandhistory/.zsh_history
      - IEX_HISTFILE=/commandhistory/.iex_history
  db:
    image: postgres
    network_mode: service:web
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db_data:
  commandhistory:
