version: "3"
services:
  web:
    volumes:
      - commandhistory:/commandhistory
    command: sleep infinity
    environment:
      - HISTFILE=/commandhistory/.zsh_history
      - IRB_HISTFILE=/commandhistory/.irb_history
volumes:
  commandhistory:
