version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace:cached
      - zsh_history:/commandhistory
    command: sleep infinity
  db:
    image: postgres
    network_mode: service:web
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    network_mode: service:web
volumes:
  db_data:
  zsh_history:
